services:
  - type: web
    name: minierp2
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DB_SERVER
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: EMPLOYEE_USERNAME
        sync: false
      - key: EMPLOYEE_PASSWORD_HASH
        sync: false
      - key: MANAGER_USERNAME
        sync: false
      - key: MANAGER_PASSWORD_HASH
        sync: false
